/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package qlsv;

import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import qlsv.model.Sinhvien;

/**
 *
 * @author LENOVO
 */
public class QLSV1 extends javax.swing.JFrame {

    ArrayList<Sinhvien> listSv = new ArrayList<>();
    DefaultTableModel model = new DefaultTableModel();
    int index;

    public QLSV1() {
        initComponents();
        setLocationRelativeTo(null);
        listSv.add(new Sinhvien("ph300", "Lê thị hai", "nữ", 8));
        listSv.add(new Sinhvien("ph301", "Lê thị thùy", "nữ", 4));
        listSv.add(new Sinhvien("ph302", "Lê thị thơ", "nữ", 10));
        listSv.add(new Sinhvien("ph303", "Lê văn huỳnh", "nam", 3));
        model = (DefaultTableModel) tblSinhvien.getModel();
        fillToTable();
        if (listSv.size() > 0) {
            index = 0;
            showDetail();
        }
        //dongHo();
        getTime();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        lblmasinhvien = new javax.swing.JLabel();
        lblhoten = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        rdogioitinh = new javax.swing.JPanel();
        rdoNam = new javax.swing.JRadioButton();
        rdoNu = new javax.swing.JRadioButton();
        lbldiemtb = new javax.swing.JLabel();
        txtmasinhvien = new javax.swing.JTextField();
        txtHoten = new javax.swing.JTextField();
        txtDiemTB = new javax.swing.JTextField();
        btnThemmoi = new javax.swing.JButton();
        btnGhi = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSinhvien = new javax.swing.JTable();
        lblThoigian = new javax.swing.JLabel();
        lblHientai = new javax.swing.JLabel();
        btnDocfile = new javax.swing.JButton();
        btnGhifile = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        lblGio = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("QUẢN LÝ SINH VIÊN");

        lblmasinhvien.setText("Mã sinh viên");

        lblhoten.setText("Họ tên");

        jLabel4.setText("Giới tính");

        rdogioitinh.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        buttonGroup1.add(rdoNam);
        rdoNam.setSelected(true);
        rdoNam.setText("Nam");

        buttonGroup1.add(rdoNu);
        rdoNu.setText("Nữ");

        javax.swing.GroupLayout rdogioitinhLayout = new javax.swing.GroupLayout(rdogioitinh);
        rdogioitinh.setLayout(rdogioitinhLayout);
        rdogioitinhLayout.setHorizontalGroup(
            rdogioitinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rdogioitinhLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rdoNam, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdoNu, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );
        rdogioitinhLayout.setVerticalGroup(
            rdogioitinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rdogioitinhLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(rdogioitinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdoNam)
                    .addComponent(rdoNu))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        lbldiemtb.setText("Điểm TB");

        btnThemmoi.setText("Thêm mới");
        btnThemmoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemmoiActionPerformed(evt);
            }
        });

        btnGhi.setText("GHi");
        btnGhi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGhiActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        tblSinhvien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã sinh viên", "Họ tên", "Giới tính", "Điểm", "Kết quả"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSinhvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSinhvienMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblSinhvien);

        lblThoigian.setText("00:00:00");

        lblHientai.setText("1/10");

        btnDocfile.setText("đọc file");
        btnDocfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDocfileActionPerformed(evt);
            }
        });

        btnGhifile.setText("Ghi file");
        btnGhifile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGhifileActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        lblGio.setText("00:00:00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblmasinhvien, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtmasinhvien, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnThemmoi)
                        .addGap(12, 12, 12)
                        .addComponent(btnThoat))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblhoten, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtHoten, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rdogioitinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbldiemtb, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDiemTB, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(lblHientai, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lblThoigian, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnGhi)
                                    .addComponent(btnDocfile))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnGhifile)
                                    .addComponent(btnXoa)
                                    .addComponent(btnUpdate)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                                .addComponent(lblGio, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(99, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnGhi, btnThemmoi, btnThoat, btnXoa});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblmasinhvien)
                            .addComponent(txtmasinhvien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnThemmoi)
                            .addComponent(btnThoat))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblhoten)
                            .addComponent(txtHoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGhi)
                            .addComponent(btnXoa))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(btnGhifile))))
                    .addComponent(btnDocfile))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rdogioitinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblThoigian)
                                .addGap(23, 23, 23))
                            .addComponent(lblGio, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbldiemtb)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtDiemTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblHientai)))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblSinhvienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSinhvienMouseClicked
        try {
            index = tblSinhvien.getSelectedRow();
            showDetail();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi click");
            return;
        }
    }//GEN-LAST:event_tblSinhvienMouseClicked

    private void btnThemmoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemmoiActionPerformed
        clearForm();
    }//GEN-LAST:event_btnThemmoiActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        int hoi = JOptionPane.showConfirmDialog(this, "Bạn có muốn thoát không");
        if (hoi == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnGhiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGhiActionPerformed
        if (txtmasinhvien.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "mã sinh viên không được rỗng");
            txtmasinhvien.requestFocus();
            return;
        }
        if (txtHoten.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "Họ tên không được rỗng");
            txtHoten.requestFocus();
            return;
        }
        if (txtDiemTB.getText().equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(this, "Điểm không được rỗng");
            txtDiemTB.requestFocus();
            return;
        }
        double diem;
        try {
            diem = Double.parseDouble(txtDiemTB.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Điểm phải là số");
            txtDiemTB.requestFocus();
            return;
        }
        if (diem < 0 || diem > 10) {
            JOptionPane.showMessageDialog(this, "Điểm phải nằm trong miền điểm");
            txtDiemTB.requestFocus();
            return;
        }
        String id = txtmasinhvien.getText();
        String hoten = txtHoten.getText();
        String gioitinh;
        if (rdoNam.isSelected()) {
            gioitinh = "Nam";
        } else {
            gioitinh = "nữ";
        }
        Sinhvien sv = new Sinhvien(id, hoten, gioitinh, diem);
        listSv.add(sv);
        model.addRow(new Object[]{sv.getId(), sv.getName(), sv.getGioitinh(), sv.getMarkAvg(), sv.getStatus(diem)});

    }//GEN-LAST:event_btnGhiActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        int hoi = JOptionPane.showConfirmDialog(this, "Ban co muon xoa khong");
        if (hoi != JOptionPane.YES_OPTION) {
            return;
        }
        listSv.remove(index);
        model.removeRow(index);
        if (listSv.size() == 0) {
            clearForm();
        } else {
            if (listSv.size() == index) {
                index--;

            }
            showDetail();
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnGhifileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGhifileActionPerformed
        try {
            ObjectOutputStream oos = new ObjectOutputStream(new FileOutputStream("txt.doc"));
            oos.writeObject(listSv);
            oos.flush();

            oos.close();

            JOptionPane.showMessageDialog(this, " ghi file oke");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "lỗi ghi file");
            return;
        }
    }//GEN-LAST:event_btnGhifileActionPerformed

    private void btnDocfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDocfileActionPerformed
        try {
            ObjectInputStream ois = new ObjectInputStream(new FileInputStream("txt.doc"));
            listSv = (ArrayList<Sinhvien>) ois.readObject();
            ois.close();
            if (listSv.size() > 0) {
                index = 0;
                showDetail();
            } else {
                clearForm();
            }
            JOptionPane.showMessageDialog(this, " đọc file oke");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "lỗi đọc file");
            return;
        }
    }//GEN-LAST:event_btnDocfileActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        String id = txtmasinhvien.getText();
        String hoten = txtHoten.getText();
        String gioitinh;
        if (rdoNam.isSelected()) {
            gioitinh = "Nam";
        } else {
            gioitinh = "nữ";
        }
        double diem = Double.parseDouble(txtDiemTB.getText());
        Sinhvien sv = new Sinhvien(id, hoten, gioitinh, diem);
        index = tblSinhvien.getSelectedRow();
        listSv.set(index, sv);
        model.setValueAt(id, index, 0);
        model.setValueAt(hoten, index, 1);
        model.setValueAt(gioitinh, index, 2);
        model.setValueAt(diem, index, 3);

        if (listSv.size() > 0) {
            fillToTable();
            index = 0;
            showDetail();
        } else {
            clearForm();
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLSV1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLSV1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLSV1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLSV1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLSV1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDocfile;
    private javax.swing.JButton btnGhi;
    private javax.swing.JButton btnGhifile;
    private javax.swing.JButton btnThemmoi;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblGio;
    private javax.swing.JLabel lblHientai;
    private javax.swing.JLabel lblThoigian;
    private javax.swing.JLabel lbldiemtb;
    private javax.swing.JLabel lblhoten;
    private javax.swing.JLabel lblmasinhvien;
    private javax.swing.JRadioButton rdoNam;
    private javax.swing.JRadioButton rdoNu;
    private javax.swing.JPanel rdogioitinh;
    private javax.swing.JTable tblSinhvien;
    private javax.swing.JTextField txtDiemTB;
    private javax.swing.JTextField txtHoten;
    private javax.swing.JTextField txtmasinhvien;
    // End of variables declaration//GEN-END:variables

    private void fillToTable() {
        model.setRowCount(0);
        for (Sinhvien sv : listSv) {
            model.addRow(new Object[]{sv.getId(), sv.getName(), sv.getGioitinh(), sv.getMarkAvg(), sv.getStatus(sv.getMarkAvg())});
        }
    }

    private void showDetail() {
        Sinhvien sv = listSv.get(index);
        txtmasinhvien.setText(sv.getId());
        txtHoten.setText(sv.getName());
        txtDiemTB.setText(sv.getMarkAvg() + "");
        String gioitinh;
        if (rdoNam.isSelected()) {
            gioitinh = "Nam";
        } else {
            gioitinh = "nữ";
        }

        tblSinhvien.setRowSelectionInterval(index, index);
        lblHientai.setText(index + 1 + "/" + listSv.size());
    }

    private void clearForm() {
        txtmasinhvien.setText("");
        txtHoten.setText("");
        txtDiemTB.setText("");

        index = -1;
        lblHientai.setText("...");
    }

    private void dongHo() {
        Thread t = new Thread() {
            @Override
            public void run() {
                SimpleDateFormat sdf = new SimpleDateFormat("hh:mm:ss aa");
                while (true) {
                    Date d = new Date();
                    lblThoigian.setText(sdf.format(d));
                    try {
                        Thread.sleep(1000);
                    } catch (Exception e) {
                    }
                }
            }

        };
        t.start();

    }

    private void getTime() {
        Thread t = new Thread() {
            @Override
            public void run() {
                int count = 0;
                int phut = 0;
                int gio = 0;
                while (true) {
                    try {
                        lblGio.setText(gio + ":" + phut + ":" + count);
                        Thread.sleep(1000);
                        count++;
                        if (count == 60) {
                            phut++;
                            count = 1;
                            lblGio.setText(gio + ":" + phut + ":" + count);
                            count++;
                            if (phut == 60) {
                                gio++;
                                count = 1;
                                phut = 0;
                                lblGio.setText(gio + ":" + phut + ":" + count);
                                count++;
                            }
                        }
                    } catch (Exception e) {
                        break;
                    }
                }
            }

        };
        t.start();
    }

}
